### PR TITLE
Installer script refactor

### PR DESCRIPTION
**Pull request by 00Asgaroth00**
This is a refactor of the installer script, the refactor tries to:

[1] Make the installer more modular
[2] Splits the steps to install into functions for for potential re-use

These changes should address the majority of current open tickets against the installer.

Tested against the following OS's

CentOS 7 64-bit
Debian 8 64-bit

Time graciously sponsored by Blueface Ltd (https://www.blueface.com)

### CODE REVIEW

**Review by lmangani — APPROVED** [review]

**Comment by lmangani** [comment]
Thanks @00Asgaroth00 and [BlueFace](https://www.blueface.com) for the contribution! 
This is overhaul of the old script is nothing short of amazing and very, very much appreciated!

**Comment by lmangani** [comment]
@00Asgaroth00 got a couple reports about debian 8 installer being partially broken and executing in non-interactive mode, investigating

**Comment by 00Asgaroth00** [comment]
Interesting, I tested with a minimal install (SSH server and Standard Utilities software groups) of Debian 8 64-bit (net install iso).
The installer for mysql is set to non interactive mode which defaults to a no password for root, the rest of the script then gathers the username/password details from the user and sets that up in a later stage.

Does this mean that we want to have the installation of mysql to be interactive for Debian?

**Comment by lmangani** [comment]
I think the mysql part being non-interactive is fine, but all the other dialogs as also skipped including the very first one to confirm installation (y/N) and so forth, ending up with a partial setup after cloning the repositories - I had a chance to briefly test it earlier and confirm this is the case - for CentOS all works as intended more or less. It seems there's another flag somewhere causing this to happen but did not have time to hunt it yet. Thanks!

**Comment by 00Asgaroth00** [comment]
can you run it with:
```
TRACE=1 ./homer-install.sh
```
And post the log. I'm guessing a failure code is not caught earlier in the script and its continuing on in error.

I'll try to replicate it here too

**Comment by 00Asgaroth00** [comment]
I've just run the installer here with a debian 8 64-bit virtual machine and the installer goes through with no issues. I can login to homer and things look okay to me here with my local test.

**Comment by 00Asgaroth00** [comment]
Just for my clarity, what do you mean by:

 "for CentOS all works as intended more or less"

Does that mean there is an issue with the CentOS side too?

**Comment by lmangani** [comment]
I will test again later on today - my test setup was a VM running regular Debian 8 w/ nothing installed and it resulted in a dialog-less (non-interactive) session with no questions asked, and a broken setup.

The only confusing bits in Centos were the lsb_release step, and the dialog related to the root mysql password input, which might be misleading since the correct action there would be to leave empty and let the system generated password be used, I guess?

**Comment by 00Asgaroth00** [comment]
Ahh okay, for CentOS, the minimal install does not install the "redhat-lsb-core" package which has the "lsb_release" app which we use to check the distribution details, I guess we could add that to the readme saying that for CentOS ensure that "redhat-lsb-core" is installed, or, the installer will exit with a message saying that the package that contains the "lsb_release" command needs to be installed (I'm guessing that this was the confusing part for you)

As for the root password for mysql, I can certainly update the script to auto-generate a password for the mysql admin user (this will apply to both Debian and CentOS) and then not prompt the user for the Admin user details of the database, I guess that does make more sense, leave that with me, I'll sort that bit out.

Just for information, the user/password details are output to a file in the root user's home directory, that way they can see what was set during installation, specifically, the file is located at:

```
~root/homer_installer_user_details
```

**Pull request merged**
